#!/bin/bash

set -euo pipefail
. /.functions

define_base_vars "${0}"

[ -v TOMCAT_NATIVE_KEYS_URL ] || fail "Don't have a TOMCAT_NATIVE_KEYS_URL to download from"
[ -v TOMCAT_NATIVE_URL ] || fail "Don't have a TOMCAT_NATIVE_URL to download from"

set_or_default TOMCAT_NATIVE_BUILD_HOME "/tomcat-native"

cleanup()
{
	[ -v SRC ] && rm -rf "${SRC}" &>/dev/null
	[ -v BUILDS ] && rm -rf "${BUILDS[@]}" &>/dev/null
}

TOMCAT_NATIVE_BUILD_HOME="$(readlink -f "${TOMCAT_NATIVE_BUILD_HOME}")"

mkdir -p "${TOMCAT_NATIVE_BUILD_HOME}"
SRC="${TOMCAT_NATIVE_BUILD_HOME}/source.tar.gz"
verified-download --keys "${TOMCAT_NATIVE_KEYS_URL}" "${TOMCAT_NATIVE_URL}" "${SRC}"
trap cleanup EXIT

JAVA_VERSIONS=(11 17 21)

running "Building for Java versions [${JAVA_VERSIONS[@]}]"
BUILDS=()
for JAVA in "${JAVA_VERSIONS[@]}" ; do
	say "Building for Java ${JAVA}..."
	set-java "${JAVA}" || fail "Failed to set the Java version to ${JAVA}"
	TARGET="${TOMCAT_NATIVE_BUILD_HOME}/${JAVA}"
	BUILD="${TARGET}.build"
	mkdir -p "${TARGET}" "${BUILD}" || fail "Failed to build the target and build directories at [${TOMCAT_NATIVE_BUILD_HOME}]"
	BUILDS+=("${BUILD}")
	(
		set -euo pipefail
		cd "${BUILD}"
		tar --strip-components=1 -xzvf "${SRC}"
		cd native
		./configure --prefix="${TARGET}"
		make
		make install
		cd "${TARGET}"
		mv -vf lib/* .
		# strip *.so *.so.* *.a
		rmdir lib
	) || fail "Build for Java ${JAVA} failed"
	ok "Build for Java ${JAVA} succeeded!"
	find "${TARGET}" -type f | sort
done
